name: social_challenge
description: "Flutter project with Clean Architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  
  # Dependency Injection
  get_it: ^7.7.0
  
  # Network
  dio: ^5.4.3+1
  
  # Navigation
  go_router: ^14.2.0
  
  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  
  # Platform Integration
  pigeon: ^17.3.0
  
  # Local Storage
  shared_preferences: ^2.2.3
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  
  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true
