// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
    let code: String
    let message: String?
    let details: Any?

    init(code: String, message: String?, details: Any?) {
        self.code = code
        self.message = message
        self.details = details
    }

    var localizedDescription: String {
        return
            "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
    }
}

private func wrapResult(_ result: Any?) -> [Any?] {
    return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
    if let pigeonError = error as? PigeonError {
        return [
            pigeonError.code,
            pigeonError.message,
            pigeonError.details,
        ]
    }
    if let flutterError = error as? FlutterError {
        return [
            flutterError.code,
            flutterError.message,
            flutterError.details,
        ]
    }
    return [
        "\(error)",
        "\(type(of: error))",
        "Stacktrace: \(Thread.callStackSymbols)",
    ]
}

private func isNullish(_ value: Any?) -> Bool {
    return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
    if value is NSNull {
        return nil
    }
    return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct NotificationPayload {
    var id: String
    var titulo: String
    var mensaje: String


    // swift-format-ignore: AlwaysUseLowerCamelCase
    static func fromList(_ pigeonVar_list: [Any?]) -> NotificationPayload? {
        let id = pigeonVar_list[0] as! String
        let titulo = pigeonVar_list[1] as! String
        let mensaje = pigeonVar_list[2] as! String

        return NotificationPayload(
            id: id,
            titulo: titulo,
            mensaje: mensaje
        )
    }

    func toList() -> [Any?] {
        return [
            id,
            titulo,
            mensaje,
        ]
    }
}

private class NativeApiPigeonCodecReader: FlutterStandardReader {
    override func readValue(ofType type: UInt8) -> Any? {
        switch type {
        case 129:
            return NotificationPayload.fromList(self.readValue() as! [Any?])
        default:
            return super.readValue(ofType: type)
        }
    }
}

private class NativeApiPigeonCodecWriter: FlutterStandardWriter {
    override func writeValue(_ value: Any) {
        if let value = value as? NotificationPayload {
            super.writeByte(129)
            super.writeValue(value.toList())
        } else {
            super.writeValue(value)
        }
    }
}

private class NativeApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
    override func reader(with data: Data) -> FlutterStandardReader {
        return NativeApiPigeonCodecReader(data: data)
    }

    override func writer(with data: NSMutableData) -> FlutterStandardWriter {
        return NativeApiPigeonCodecWriter(data: data)
    }
}

class NativeApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
    static let shared = NativeApiPigeonCodec(readerWriter: NativeApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeService {
    func sendLocalNotification(payload: NotificationPayload) throws
    func requestNotificationPermission() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeServiceSetup {
    static var codec: FlutterStandardMessageCodec {
        NativeApiPigeonCodec.shared
    }

    /// Sets up an instance of `NativeService` to handle messages through the `binaryMessenger`.
    static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeService?, messageChannelSuffix: String = "") {
        let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
        let sendLocalNotificationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.social_challenge.NativeService.sendLocalNotification\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
        if let api = api {
            sendLocalNotificationChannel.setMessageHandler { message, reply in
                let args = message as! [Any?]
                let payloadArg = args[0] as! NotificationPayload
                do {
                    try api.sendLocalNotification(payload: payloadArg)
                    reply(wrapResult(nil))
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            sendLocalNotificationChannel.setMessageHandler(nil)
        }
        let requestNotificationPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.social_challenge.NativeService.requestNotificationPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
        if let api = api {
            requestNotificationPermissionChannel.setMessageHandler { _, reply in
                do {
                    let result = try api.requestNotificationPermission()
                    reply(wrapResult(result))
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            requestNotificationPermissionChannel.setMessageHandler(nil)
        }
    }
}
